#!/usr/bin/env python3
"""Write results/SHA256SUMS -- the archive manifest of the released artifact.

The manuscript's data-availability statement lists "an archive manifest with
SHA-256 digests" among the supplementary files, and states that every
supplementary file is regenerated by the same reproduction script as the main
results.  This script is what ``reproduce.sh`` calls to do that, so the manifest
is a product of the reproduction run rather than a hand-maintained file.

What it digests
---------------
  * every file under results/ (the regenerated data, figures and supplementary
    tables), except the manifest itself;
  * the artifact's source and metadata files -- the explicit SOURCE_FILES list plus the
    SOURCE_DIRS trees (engine/, ruleset/, profiles/, experiments/, docs/) -- so a reader
    can tell whether the tree that produced the numbers is the tree they are holding,
    including the research design record under docs/.

What it deliberately ignores
----------------------------
  dist/               release archives are digested separately by make_release.py,
                      which writes dist/SHA256SUMS over the packages themselves;
  .venv/ __pycache__/ .DS_Store
                      build and environment noise, not artifact content.

Output format is the standard ``<digest>  <path>``, paths relative to the
artifact root using forward slashes, sorted, LF line endings, no timestamps --
so the file is byte-identical across runs on the same content.

Usage
-----
    python3 make_manifest.py            # write results/SHA256SUMS
    python3 make_manifest.py --check    # verify an existing manifest, exit 1 on drift
"""
from __future__ import annotations

import hashlib
import os
import sys

_ROOT = os.path.dirname(os.path.abspath(__file__))
RESULTS = os.path.join(_ROOT, "results")
MANIFEST = os.path.join(RESULTS, "SHA256SUMS")

SKIP_DIRS = {"dist", ".venv", "__pycache__", ".git", ".mypy_cache",
             ".pytest_cache", ".ipynb_checkpoints"}
SKIP_NAMES = {".DS_Store", "SHA256SUMS"}

# Source and metadata files: the artifact's own content, outside results/.
#
# These two lists are exhaustive by construction: collect() walks results/, but it does
# not walk the artifact root, so anything outside results/ is digested only if it is
# named here. A new top-level file or directory is therefore distributed *and not
# digested* unless it is added below -- and nothing fails, because check() uses this
# same list as its definition of "present". docs/ was added for exactly this reason.
SOURCE_FILES = [
    # .gitignore ships in every archive (make_release.py does not exclude it), so it must be
    # digested too -- otherwise a change to it would be the one distributed file the manifest
    # could not see. SKIP_NAMES below excludes only the manifest itself, which cannot digest
    # itself; that exclusion is by design and is the second unavoidable gap in coverage.
    ".gitignore",
    "VERSION", "CHANGELOG.md", "CITATION.cff", "LICENSE", "LICENSE-DATA",
    "NOTICE", "README.md", "RELEASE.md", "RESULTS.md", "Makefile",
    "reproduce.sh", "make_release.py", "make_manifest.py",
    "run_all.py", "run_stress_sensitivity.py", "verify_results.py",
]
SOURCE_DIRS = ["engine", "ruleset", "profiles", "experiments", "docs"]


def sha256(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def collect() -> list[str]:
    rels: list[str] = []

    for dirpath, dirnames, filenames in os.walk(RESULTS):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for fn in filenames:
            if fn in SKIP_NAMES or fn.endswith(".pyc"):
                continue
            rels.append(os.path.relpath(os.path.join(dirpath, fn), _ROOT))

    for rel in SOURCE_FILES:
        if os.path.exists(os.path.join(_ROOT, rel)):
            rels.append(rel)
    for d in SOURCE_DIRS:
        base = os.path.join(_ROOT, d)
        for dirpath, dirnames, filenames in os.walk(base):
            dirnames[:] = [x for x in dirnames if x not in SKIP_DIRS]
            for fn in filenames:
                if fn in SKIP_NAMES or fn.endswith(".pyc"):
                    continue
                rels.append(os.path.relpath(os.path.join(dirpath, fn), _ROOT))

    return sorted(set(r.replace(os.sep, "/") for r in rels))


def write() -> int:
    rels = collect()
    os.makedirs(RESULTS, exist_ok=True)
    with open(MANIFEST, "w", encoding="utf-8", newline="\n") as fh:
        for rel in rels:
            fh.write(f"{sha256(os.path.join(_ROOT, rel))}  {rel}\n")
    print(f"[written] results/SHA256SUMS  ({len(rels)} files)")
    return 0


def check() -> int:
    if not os.path.exists(MANIFEST):
        print("MISSING results/SHA256SUMS -- run reproduce.sh first")
        return 1
    want = {}
    with open(MANIFEST, encoding="utf-8") as fh:
        for line in fh:
            line = line.rstrip("\n")
            if not line:
                continue
            digest, _, rel = line.partition("  ")
            want[rel] = digest
    have = set(collect())
    problems = []
    for rel in sorted(set(want) - have):
        problems.append(f"listed but absent: {rel}")
    for rel in sorted(have - set(want)):
        problems.append(f"present but not listed: {rel}")
    for rel in sorted(set(want) & have):
        got = sha256(os.path.join(_ROOT, rel))
        if got != want[rel]:
            problems.append(f"digest mismatch: {rel} (got {got[:12]}, want {want[rel][:12]})")
    if problems:
        print(f"MANIFEST: FAIL -- {len(problems)} problem(s)")
        for p in problems[:20]:
            print(f"  - {p}")
        return 1
    print(f"MANIFEST: OK -- {len(want)} files match results/SHA256SUMS")
    return 0


if __name__ == "__main__":
    raise SystemExit(check() if "--check" in sys.argv else write())
